# Generated by Django 5.0.7 on 2024-08-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("product", models.ManyToManyField(to="green_app.product")),
            ],
        ),
    ]
