# Generated by Django 5.0.7 on 2024-08-11 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0003_remove_wishlist_product_items_wishlist_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="wishlist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="green_app.wishlist",
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="prodInfo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="green_app.productinfo",
            ),
        ),
    ]
