# Generated by Django 5.0.7 on 2024-08-12 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0004_profile_wishlist_alter_items_prodinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="wishlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="green_app.wishlist",
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("items", models.ManyToManyField(to="green_app.items")),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="green_app.cart",
            ),
        ),
    ]
