# Generated by Django 5.0.7 on 2024-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0005_alter_profile_wishlist_cart_profile_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
