# Generated by Django 5.0.7 on 2024-08-15 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0006_alter_wishlist_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="orderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placedAt", models.DateTimeField(auto_now_add=True)),
                ("placedDate", models.DateField(auto_now_add=True)),
                ("placedTime", models.TimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("delivered", "Delivered"),
                            ("inprogress", "In Progress"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gift",
                    models.CharField(
                        choices=[("Yes", "yes"), ("No", "no")], max_length=20
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="green_app.profile",
                    ),
                ),
            ],
        ),
    ]
