# Generated by Django 5.0.7 on 2024-08-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0008_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="reviewimg/"),
        ),
    ]
