# Generated by Django 5.0.7 on 2024-08-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0009_alter_reviews_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
    ]
