# Generated by Django 5.0.7 on 2024-08-16 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0010_product_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="ratings",
            field=models.FloatField(
                help_text="Rate between 1 (lowest) to 5 (highest)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
