# Generated by Django 5.0.7 on 2024-08-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0012_subscription_remove_orderdetails_placeddate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(default=1),
        ),
    ]
