# Generated by Django 5.0.7 on 2024-08-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0017_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="gloss",
        ),
        migrations.AddField(
            model_name="productinfo",
            name="gloss",
            field=models.CharField(
                choices=[("High", "high"), ("Low", "low")], max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
