# Generated by Django 5.0.7 on 2024-08-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0018_remove_product_gloss_productinfo_gloss_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.SmallIntegerField(null=True),
        ),
    ]
