# Generated by Django 5.0.7 on 2024-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0019_remove_product_size_product_height_product_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="inventory",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
