# Generated by Django 5.0.7 on 2024-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0021_alter_productinfo_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="gift",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], max_length=20
            ),
        ),
    ]
