# Generated by Django 5.0.7 on 2024-08-23 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0023_alter_orderdetails_gift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="green_app.cart",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="wishlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="green_app.wishlist",
            ),
        ),
    ]
