# Generated by Django 5.0.7 on 2024-08-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0025_alter_productinfo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="drainage",
            field=models.CharField(
                choices=[("Yes", "yes"), ("No", "no")], max_length=3
            ),
        ),
    ]
