# Generated by Django 5.0.7 on 2024-08-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0026_alter_items_drainage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="drainage",
        ),
        migrations.RemoveField(
            model_name="items",
            name="gloss",
        ),
        migrations.RemoveField(
            model_name="product",
            name="drainage",
        ),
        migrations.AddField(
            model_name="productinfo",
            name="drainage",
            field=models.CharField(
                choices=[("Yes", "yes"), ("No", "no")], max_length=3, null=True
            ),
        ),
    ]
