# Generated by Django 5.0.7 on 2024-08-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0028_remove_productinfo_drainage_items_drainage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="drainage",
            field=models.CharField(
                choices=[("Both", "both"), ("Yes", "yes"), ("No", "no")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="drainage",
            field=models.CharField(
                choices=[("Both", "both"), ("Yes", "yes"), ("No", "no")],
                max_length=4,
                null=True,
            ),
        ),
    ]
