# Generated by Django 5.0.7 on 2024-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0030_alter_items_drainage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinfo",
            name="price",
            field=models.PositiveBigIntegerField(),
        ),
    ]
