# Generated by Django 5.0.7 on 2024-08-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0031_alter_productinfo_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="FishNChips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping", models.PositiveIntegerField(default=500, null=True)),
                ("giftwrap", models.PositiveIntegerField(default=100, null=True)),
            ],
        ),
    ]
