# Generated by Django 5.0.7 on 2024-08-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0032_fishnchips"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetails",
            name="grandTotal",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
