# Generated by Django 5.0.7 on 2024-08-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0034_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetails",
            name="orderItems",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="green_app.cart",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="categories/"),
        ),
    ]
