# Generated by Django 5.0.7 on 2024-08-25 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0037_remove_orderdetails_orderitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetails",
            name="orderItems",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="green_app.cart",
            ),
        ),
    ]
