# Generated by Django 5.0.7 on 2024-08-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0043_alter_cart_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetails",
            name="paymentProof",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="payment/"
            ),
        ),
    ]
