# Generated by Django 5.0.7 on 2024-08-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0044_orderdetails_paymentproof"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetails",
            name="paymentMethod",
            field=models.CharField(
                choices=[("online", "Online"), ("COD", "cod")], max_length=6, null=True
            ),
        ),
    ]
