# Generated by Django 5.0.7 on 2024-08-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0046_alter_orderdetails_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="image",
        ),
    ]
