# Generated by Django 5.0.7 on 2024-08-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0047_remove_subcategory_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(max_length=90),
        ),
    ]
