# Generated by Django 5.0.7 on 2024-08-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0048_alter_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishnchips",
            name="accountName",
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="fishnchips",
            name="accountNumber",
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="fishnchips",
            name="paymentName",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="fishnchips",
            name="paymentNumber",
            field=models.CharField(help_text="03XXXXXXXXX", max_length=11, null=True),
        ),
    ]
