# Generated by Django 5.0.7 on 2024-08-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0049_fishnchips_accountname_fishnchips_accountnumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetails",
            name="paymentStatus",
            field=models.CharField(
                choices=[("paid", "Paid"), ("Pending", "pending")],
                max_length=7,
                null=True,
            ),
        ),
    ]
