# Generated by Django 5.0.7 on 2024-08-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("green_app", "0051_alter_orderdetails_paymentstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="gift",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], max_length=20
            ),
        ),
    ]
